services:
  - type: web
    name: shabian-portfolio
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan deploy:render
    startCommand: bash start.sh
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://shabian-portfolio.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: shabian-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: shabian-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: shabian-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: shabian-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: shabian-db
          property: password
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: shabianarsyl@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: shabianarsyl@gmail.com
      - key: MAIL_FROM_NAME
        value: "Shabian Arsyl Yonanta"

databases:
  - name: shabian-db
    plan: free
    databaseType: postgresql
    ipAllowList: []
